Traceback (most recent call last):
  File "/tmp/code.py", line 78, in <module>
    attractive_force = distance**2 / k
                       ~~~~~~~~^^~
OverflowError: (34, 'Numerical result out of range')
